In [2]:
import numpy as np

arr = np.random.uniform(10, 100, [100,2])
print (arr)

[[73.54563383 60.46232932]
 [93.7404153  46.66042301]
 [82.09350798 52.49402263]
 [56.21609496 22.096572  ]
 [43.52630038 84.47954205]
 [21.62861549 29.3458942 ]
 [42.45659173 44.56350673]
 [91.45324072 91.49985863]
 [44.19511771 40.31209412]
 [41.77990032 23.22498704]
 [16.83503475 87.74425755]
 [64.03228782 24.68977401]
 [66.04607408 50.27263812]
 [48.98308398 24.47586602]
 [51.07184653 45.3125615 ]
 [42.86582064 19.8113089 ]
 [78.64251437 14.92329218]
 [76.03693546 31.69097349]
 [31.64512182 77.26688932]
 [75.16215843 38.93465113]
 [35.90236146 75.72729803]
 [25.22658311 62.54157004]
 [55.34368346 12.49939285]
 [31.29144811 47.59793316]
 [91.81528988 57.64119826]
 [60.56854291 73.94284791]
 [34.01331538 77.61408831]
 [19.58964875 92.80428271]
 [70.76694858 28.68590159]
 [18.04886726 19.16699024]
 [29.81786843 76.88040449]
 [49.3892819  56.58582714]
 [46.93366238 74.88946425]
 [82.78169709 42.31771335]
 [62.45066191 84.37050844]
 [49.29595791 87.05416669]
 [79.22897245 44.69104336]
 

In [6]:
mat = np.random.uniform(1,100,[10,3])
print (mat)

[[29.00442457 23.27191634 49.76104525]
 [30.05649386 35.48370516 78.27787677]
 [32.49984386 72.01740304 19.88606994]
 [88.18333943 90.43266817 79.91692279]
 [94.83894609  8.24122529  2.65894122]
 [18.00173374  9.02777338 70.05634213]
 [84.20884443 39.73104494 81.32693743]
 [65.23059075 14.96745324 96.0247858 ]
 [78.25237273 44.4665196  61.97026817]
 [35.13434377  3.16973815 83.53900008]]
